name: tubes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.1.2 <4.0.0'

dependencies:
    auto_size_text: 3.0.0

    cupertino_icons: 1.0.2
    flutter:
        sdk: flutter
    http: ^0.13.6
    flutter_animate: 4.1.1+1
    flutterflow_ui: 0.2.0+1
    font_awesome_flutter: 10.1.0
    google_fonts: 4.0.3

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
